parameters:
    oauth2.server.class: OAuth2\Server
    oauth2.request.class: OAuthBundle\Manager\Request
    oauth2.response.class: OAuth2\HttpFoundationBridge\Response
    oauth2.storage.client_credentials.class: OAuthBundle\Storage\ClientCredentials
    oauth2.storage.access_token.class: OAuthBundle\Storage\AccessToken
    oauth2.storage.authorization_code.class: OAuthBundle\Storage\AuthorizationCode
    oauth2.storage.user_credentials.class: OAuthBundle\Storage\UserCredentials
    oauth2.storage.refresh_token.class: OAuthBundle\Storage\RefreshToken
    oauth2.storage.scope.class: OAuthBundle\Storage\Scope
    oauth2.storage.public_key.class: OAuth2\Storage\Memory
    oauth2.grant_type.client_credentials.class: OAuth2\GrantType\ClientCredentials
    oauth2.grant_type.authorization_code.class: OAuth2\GrantType\AuthorizationCode
    oauth2.grant_type.refresh_token.class: OAuth2\GrantType\RefreshToken
    oauth2.grant_type.user_credentials.class: OAuth2\GrantType\UserCredentials
    oauth2.user_provider.class: OAuthBundle\User\OAuth2UserProvider
    oauth2.client_manager.class: OAuthBundle\Manager\ClientManager
    oauth2.scope_manager.class: OAuthBundle\Manager\ScopeManager

services:
    oauth2.server:
        class: %oauth2.server.class%
        arguments:
            oauth2.server.storage: 
                - "@oauth2.storage.client_credentials"
                - "@oauth2.storage.access_token"
                - "@oauth2.storage.authorization_code"
                - "@oauth2.storage.user_credentials"
                - "@oauth2.storage.refresh_token"
                - "@oauth2.storage.scope"
            oauth2.server.config:
                access_lifetime: 86400

    oauth.security.authentication.provider:
        class: OAuthBundle\Security\Authentication\Provider\OAuthProvider
        arguments:
            - '@oauth2.user_provider'
            - '%kernel.cache_dir%/security/nonces'
        public: false

    oauth.security.authentication.listener:
        class: OAuthBundle\Security\Firewall\OAuthListener
        arguments: ['@security.token_storage', '@security.authentication.manager','@doctrine.orm.entity_manager']
        public: false

    oauth2.request:
        class: %oauth2.request.class%
        arguments: 
            - "@request_stack"

    oauth2.response:
        class: %oauth2.response.class%

    oauth2.user_provider:
        class: %oauth2.user_provider.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.encoder_factory"
            - "@wordpress_user.user_manager"

    oauth2.scope_manager:
        class: %oauth2.scope_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    oauth2.client_manager:
        class: %oauth2.client_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@oauth2.scope_manager"

    oauth2.storage.client_credentials:
        class: %oauth2.storage.client_credentials.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    oauth2.storage.authorization_code:
        class: %oauth2.storage.authorization_code.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    oauth2.storage.user_credentials:
        class: %oauth2.storage.user_credentials.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@oauth2.user_provider"
            - "@wordpress_sha1_encoder"

    oauth2.storage.access_token:
        class: %oauth2.storage.access_token.class%
        arguments: 
            - "@doctrine.orm.entity_manager"

    oauth2.storage.refresh_token:
        class: %oauth2.storage.refresh_token.class%
        arguments: 
            - "@doctrine.orm.entity_manager"

    oauth2.storage.scope:
        class: %oauth2.storage.scope.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@oauth2.scope_manager"

    oauth2.storage.public_key:
        class: %oauth2.storage.public_key.class%

    oauth2.grant_type.client_credentials:
        class: %oauth2.grant_type.client_credentials.class%
        arguments:
            - "@oauth2.storage.client_credentials"

    oauth2.grant_type.authorization_code:
        class: %oauth2.grant_type.authorization_code.class%
        arguments:
            - "@oauth2.storage.authorization_code"

    oauth2.grant_type.user_credentials:
        class: %oauth2.grant_type.user_credentials.class%
        arguments:
            - "@oauth2.storage.user_credentials"

    oauth2.grant_type.refresh_token:
        class: %oauth2.grant_type.refresh_token.class%
        arguments:
            - "@oauth2.storage.refresh_token"