services:
    oauth.listener.decorating_deserialize:
        class: 'OAuthBundle\EventListener\DeserializeListener'
        arguments: ['@api_platform.serializer', '@api_platform.serializer.context_builder', '@api_platform.listener.request.deserialize']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2 }