services:
    post.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact' , postType: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'post.search' } ]

    postmeta.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { metaId: 'exact', postId: 'exact', metaKey: 'exact', metaValue: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'postmeta.search' } ]

    term.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { termId: 'exact', name: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'term.search' } ]

    option.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { optionId: 'exact', optionName: 'exact', optionValue: 'partial'} ]
        tags:      [ { name: 'api_platform.filter', id: 'option.search' } ]
    
    link.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { linkId: 'exact', linkUrl: 'exact', linkName: 'exact'} ]
        tags:      [ { name: 'api_platform.filter', id: 'link.search' } ]

    comment.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { commentId: 'exact', commentAuthor: 'exact', userId: 'exact'} ]
        tags:      [ { name: 'api_platform.filter', id: 'comment.search' } ]

    commentmeta.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { metaId: 'exact', metaKey: 'exact', commentId: 'exact'} ]
        tags:      [ { name: 'api_platform.filter', id: 'commentmeta.search' } ]

    termmeta.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { metaId: 'exact', metaKey: 'exact', termId: 'exact'} ]
        tags:      [ { name: 'api_platform.filter', id: 'termmeta.search' } ]

    term_relationship.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { objectId: 'exact', termTaxonomyId: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'term_relationship.search' } ]

    term_taxonomy.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { termTaxonomyId: 'exact', termId: 'exact', taxonomy: 'exact', parent: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'term_taxonomy.search' } ]
