api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@WordPressBundle/Action/'
    type:     'annotation'


o_auth:
    resource: "@OAuthBundle/Controller/"
    type:     annotation
    prefix:   /
