# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        WordPressBundle\Entity\User:
            id: wordpress_sha1_encoder
    providers:
        wordpress_provider:
            id: oauth2.user_provider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/((?!docs|oauth).)*$
            stateless:  true
            oauth: true
